Models/Entities/Register.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskMvc.Models.Entities
{
    public class Register
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required(ErrorMessage = "Ad alanı gereklidir.")]
        [StringLength(100, ErrorMessage = "Ad en fazla 100 karakter olmalıdır.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Soyad alanı gereklidir.")]
        [StringLength(100, ErrorMessage = "Soyad en fazla 100 karakter olmalıdır.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "E-posta alanı gereklidir.")]
        [EmailAddress(ErrorMessage = "Geçersiz e-posta adresi.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Şifre alanı gereklidir.")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Şifre en az 6 karakter olmalıdır.")]
        public string Password { get; set; }

        [NotMapped] // Bu özellik veritabanında saklanmayacak
        public IFormFile ProfileImage { get; set; }
        public string? ProfileImagePath { get; set; }
    }
}

Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Mvc;
using TaskMvc.Models;
using System.Xml.Linq;
using TaskMvc.Business;
using System.Xml.Serialization;
using System.IO;
using TaskMvc.Interface;


namespace TaskMvc.Controllers
{
    public class FileUploadController : Controller
    {

        private readonly IFileUploadService _fileUploadService;
        private readonly IFileSaveService _fileSaveService;


        public FileUploadController(IFileUploadService fileUploadService, IFileSaveService fileSaveService)
        {
            _fileUploadService = fileUploadService;
            _fileSaveService = fileSaveService;
        }


        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            var path="";
            if (file == null || file.Length == 0)
            {
                return BadRequest("Dosya seçilmedi.");
            }
            try
            {
                path = await _fileUploadService.UploadFileAsync(file);
                var genelBilgiler = await _fileSaveService.DeserializeXmlAsync(path);  //genelBilgiler daha sonra kullanılabilir.

                return Ok("Dosya başarıyla yüklendi ve ayrıştırıldı.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Sunucu hatası: " + ex.Message);
            }

        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TaskMvc.Models;

namespace TaskMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Excel()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }


    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TaskMvc.Business;
using TaskMvc.Interface;
using TaskMvc.Models.Entities;

namespace TaskMvc.Controllers
{
    public class UserController : Controller
    {

        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpPost]
        public async Task<IActionResult> Register(Register model, IFormFile profileImage)
        {
            if (ModelState.IsValid)
            {
                await _userService.RegisterUserAsync(model, profileImage);

                return RedirectToAction("Index", "Home");
            }
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage); // Hangi hata mesajının döndüğünü kontrol edin
                }
            }
            // Model geçersizse, formu yeniden göster
            return View();
        }
    }
}

Views/Home/Excel.cshtml
@{
    ViewData["Title"] = "Excel Oluştur";
}

<h1>@ViewData["Title"]</h1>

<div class="text-center">
    <button id="downloadButton" class="btn btn-primary" onclick="window.location.href='@Url.Action("DownloadExcel", "FileDownload")'">
        Excel Oluştur
    </button>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Dosya Yükle</h1>

    <div style="margin-bottom: 10px;">
        <input type="file" id="fileInput" accept=".xml" style="display:none;" />
        <button id="fileSelectButton" class="btn btn-primary">Dosya Yükle</button>
        <span id="fileName" style="margin-left: 10px;">No file chosen</span>
    </div>
    <div id="result" style="margin-top: 10px;"></div>
</div>

@section Scripts {
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            $(document).ready(function () {
                $("#fileSelectButton").click(function () {
                    $("#fileInput").click();
                });

                $("#fileInput").change(function () {
                    var fileInput = document.getElementById('fileInput');
                    var fileNameDisplay = $("#fileName");

                    if (fileInput.files.length === 0) {
                        fileNameDisplay.text("No file chosen");
                        alert("Lütfen bir dosya seçin.");
                        return;
                    }

                    fileNameDisplay.text(fileInput.files[0].name);

                    var formData = new FormData();
                    formData.append("file", fileInput.files[0]);

                    $.ajax({
                        url: '@Url.Action("Upload", "FileUpload")',
                        type: 'POST',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function (response) {
                            $("#result").html("Dosya başarıyla yüklendi!");
                            alert("Dosya başarıyla yüklendi!");
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            alert("Hata: " + errorThrown);
                        }
                    });
                });
            });
        </script>
}

<style>
    .btn {
        padding: 6px 12px;
        cursor: pointer;
        margin-top: 10px;
    }
</style>

Views/Home/Register.cshtml
@model TaskMvc.Models.Entities.Register

@{
    ViewData["Title"] = "Kayıt Ol";
}


<h2>@ViewData["Title"]</h2>

<form asp-controller="User" asp-action="Register" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" type="password" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ProfileImage"></label>
        <input asp-for="ProfileImage" class="form-control" type="file" />
        <span asp-validation-for="ProfileImage" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Kayıt Ol</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}